site_name: BigFunctions
site_description: "BigFunctions are open-source BigQuery routines that give you SQL-superpowers in BigQuery. BigFunctions can show data-visualizations inside BigQuery console, compute advanced transforms such as sentiment score of a text, or send data to any of your favorite SAAS tool. BigFunctions is dbt-friendly."
site_url: 'https://unytics.io/bigfunctions/'
repo_name: 'unytics/bigfunctions'
repo_url: 'https://github.com/unytics/bigfunctions'
edit_uri: 'edit/main/site/content'
copyright: 'Copyright &copy; 2022 Unytics'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: site/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - tabs
    - content.tabs.link
    - instant
    # - toc.integrate
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    - navigation.expand

markdown_extensions:
  - attr_list
  - tables
  - toc:
      toc_depth: 4
      permalink: "Â¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins: []
nav:
  - Home: index.md
  - BigFunctions: reference.md
  - Getting Started: getting_started.md

bigfunctions_categories:
  - name: "explore"
    emoticon: "ðŸ‘€"
    title: "Explore data within BigQuery console"
    subtitle: "Make computations on BigQuery and display the results as data-vizualizations directly in BigQuery console."
  - name: "transform_string"
    emoticon: "âœ¨"
    title: "Transform data creatively"
    subtitle: "Be amazed with your new SQL powers."
  - name: "transform_date"
    emoticon: "ðŸ“†"
    title: "Transform data creatively"
    subtitle: "Be amazed with your new SQL powers."
  - name: "graph"
    emoticon: "ðŸŒ"
    title: "Graph Algorithms"
    subtitle: "No need for neo4j nor spark graphframes --> go BigQuery boosted by BigFunctions!"
  - name: "notify"
    emoticon: "ðŸ’¬"
    title: "Send infos to your customers, alert the operations teams, send reportings to business"
    subtitle: "Spread the word to the world!"
  - name: "export"
    emoticon: "ðŸš€"
    title: "Get the data out to the outside world"
    subtitle: "Make BigQuery as the golden source of all your SAAS and for all your usages"
  - name: "utils"
    emoticon: "ðŸ”¨"
    title: "Utils BigFunctions"
    subtitle: ""
bigfunctions_datasets:
  - name: "bigfunctions.eu"
    region: "EU"
  - name: "bigfunctions.us"
    region: "US"
  - name: "bigfunctions.europe_west1"
    region: "europe-west1"
  - name: "bigfunctions.your_region2"
    region: "your-region2"