site_name: BigFunctions
site_description: "BigFunctions are open-source BigQuery funcions that give you SQL-superpowers. BigFunctions can compute advanced transforms such as sentiment score of a text, or send data to any of your favorite SAAS tool. BigFunctions is dbt's best friend."
site_url: 'https://unytics.io/bigfunctions/'
repo_name: 'unytics/bigfunctions'
repo_url: 'https://github.com/unytics/bigfunctions'
edit_uri: 'edit/main'
copyright: 'Built by <a href="https://unytics.io"><u>Unytics</u></a> — Copyright &copy; 2025'
theme:
  name: material
  custom_dir: docs/theme_overrides
  logo: assets/logo.png
  favicon: /assets/favicon.ico
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    # - instant
    # - toc.integrate
    # - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    # - navigation.expand


markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
      permalink: "¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - extra.css

plugins:
  - search
nav:
  - Home: index.md
  - BigFunctions: bigfunctions/README.md
  - Framework: framework.md
  - Community:
      - Join the Community: community.md
      - Join Slack: https://join.slack.com/t/unytics/shared_invite/zt-1gbv491mu-cs03EJbQ1fsHdQMcFN7E1Q
      - Add a star on GitHub: https://github.com/unytics/bigfunctions
      - Suggest a function: https://github.com/unytics/bigfunctions/issues/new?assignees=&labels=new-bigfunction&projects=&template=0_new_bigfunction.yaml&title=%5Bnew%5D%3A+%60function_name%28argument1%2C+argument2%29%60
      - Report a bug: https://github.com/unytics/bigfunctions/issues/new/choose
  - Blog: blog/index.md
  - Chat with us: chat_with_us.md
validation:
  nav:
    omitted_files: ignore
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unytics/bigfunctions
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/unytics/shared_invite/zt-1gbv491mu-cs03EJbQ1fsHdQMcFN7E1Q
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/unytics/
