site_name: BigFunctions
site_description: "BigFunctions are open-source BigQuery routines that give you SQL-superpowers. BigFunctions can compute advanced transforms such as sentiment score of a text, or send data to any of your favorite SAAS tool. BigFunctions is dbt's best friend."
site_url: 'https://unytics.io/bigfunctions/'
repo_name: 'unytics/bigfunctions'
repo_url: 'https://github.com/unytics/bigfunctions'
edit_uri: 'edit/main'
copyright: 'Copyright &copy; 2024 Unytics'
theme:
  name: material
  custom_dir: docs/theme_overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
    # - instant
    # - toc.integrate
    # - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    # - navigation.expand
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
      permalink: "Â¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
nav:
  - Get Started!: README.md
  - Explore BigFunctions!: bigfunctions/README.md
  - Contribute!: CONTRIBUTING.md
validation:
  nav:
    omitted_files: ignore
bigfunctions_categories:
  - name: "AI"
    emoticon: "ğŸ§ "
  - name: "notify"
    emoticon: "ğŸ’¬"
  - name: "get_data"
    emoticon: "ğŸ›¢"
  - name: "export"
    emoticon: "ğŸš€"
  - name: "transform_numeric"
    emoticon: "1ï¸âƒ£"
  - name: "transform_string"
    emoticon: "âœ¨"
  - name: "transform_geo_data"
    emoticon: "ğŸŒ"
  - name: "transform_date"
    emoticon: "ğŸ“†"
  - name: "transform_json"
    emoticon: "<span style=\"color: var(--md-primary-fg-color);\">{...}</span>"
  - name: "transform_array"
    emoticon: "<span style=\"color: var(--md-primary-fg-color);\">[...]</span>"
  - name: "machine_learning"
    emoticon: "ğŸ§ "
  - name: "graph"
    emoticon: "ğŸŒ"
  - name: "convert_data_format"
    emoticon: "ğŸ”¨"
  - name: "explore"
    emoticon: "ğŸ‘€"
  - name: "utils"
    emoticon: "ğŸ”¨"
