site_name: BigFunctions
site_description: "BigFunctions are open-source BigQuery routines that give you SQL-superpowers. BigFunctions can show data-visualizations inside BigQuery console, compute advanced transforms such as sentiment score of a text, or send data to any of your favorite SAAS tool. BigFunctions is dbt's best friend."
site_url: 'https://unytics.io/bigfunctions/'
repo_name: 'unytics/bigfunctions'
repo_url: 'https://github.com/unytics/bigfunctions'
edit_uri: 'edit/main/site/content'
copyright: 'Copyright &copy; 2023 Unytics'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: site/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
    - instant
    # - toc.integrate
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    - navigation.expand

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
      permalink: "¬∂"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins: []
nav:
  - Home: index.md
  - BigFunctions: reference.md
  - Getting Started: getting_started.md
  - Contribute!: contribute.md

bigfunctions_categories:
  - name: "get_data"
    emoticon: "üõ¢"
    title: "Get Data"
    subtitle: "Get data from any API or any website!"
  - name: "notify"
    emoticon: "üí¨"
    title: "Send infos to your customers, alert the operations teams, send reportings to business"
    subtitle: "Spread the word to the world!"
  - name: "transform_numeric"
    emoticon: "1Ô∏è‚É£"
    title: "Transform data creatively"
  - name: "transform_string"
    emoticon: "‚ú®"
    title: "Transform data creatively"
    subtitle: "Be amazed with your new SQL powers."
  - name: "transform_geo_data"
    emoticon: "üåê"
    title: "Geo Functions"
  - name: "transform_date"
    emoticon: "üìÜ"
    title: "Transform data creatively"
    subtitle: "Be amazed with your new SQL powers."
  - name: "transform_json"
    emoticon: "<span style=\"color: var(--md-primary-fg-color);\">{...}</span>"
    title: "BigQuery json made easy"
    subtitle: "Be amazed with your new SQL powers."
  - name: "transform_array"
    emoticon: "<span style=\"color: var(--md-primary-fg-color);\">[...]</span>"
    title: "BigQuery arrays made easy"
    subtitle: "Be amazed with your new SQL powers."
  - name: "machine_learning"
    emoticon: "üß†"
  - name: "graph"
    emoticon: "üåê"
    title: "Graph Algorithms"
    subtitle: "No need for neo4j nor spark graphframes --> go BigQuery boosted by BigFunctions!"
  - name: "convert_data_format"
    emoticon: "üî®"
    title: "Convert data format"
    subtitle: ""
  - name: "export"
    emoticon: "üöÄ"
    title: "Get the data out to the outside world"
    subtitle: "Make BigQuery as the golden source of all your SAAS and for all your usages"
  - name: "explore"
    emoticon: "üëÄ"
    title: "Explore data within BigQuery console"
    subtitle: "Make computations on BigQuery and display the results as data-vizualizations directly in BigQuery console."
  - name: "utils"
    emoticon: "üî®"
    title: "Utils BigFunctions"
    subtitle: ""
bigfunctions_datasets:
  - name: "bigfunctions.eu"
    region: "EU"
  - name: "bigfunctions.us"
    region: "US"
  - name: "bigfunctions.europe_west1"
    region: "europe-west1"
  - name: "bigfunctions.your_region2"
    region: "your-region2"