site_name: BigFunctions
repo_name: 'unytics/bigfunctions'
repo_url: 'https://github.com/unytics/bigfunctions'
edit_uri: 'edit/main'
theme:
  name: material
  # custom_dir: docs/theme_overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
    # - instant
    # - toc.integrate
    # - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    # - navigation.expand
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
      permalink: "Â¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
nav:
  - Get Started!: README.md
  - Explore BigFunctions!: bigfunctions/README.md
validation:
  nav:
    omitted_files: ignore
