type: function_sql
author: "Benjamin Tabet"
description: |-
  Return the sum of array values
arguments:
  - name: arr
    type: any type
output:
  name: value
  type: any type
examples:
  - description: ""
    arguments:
      - [1, 4, 3]
    output: "8"
code: select sum(value) from unnest(arr) value
